### ISSUE TITLE
heya, you got an ssh private key hanging out on the internet there

### ISSUE THREAD

**Issue by ava-dylang** [CumulusNetworks/ansible-push-keys#1]
thought you ought'a know.

**Comment by ericpulvino** [comment]
Thanks for noticing. This is actually on purpose.... while called a private key there is nothing private about it. You might recognize it as the key from Vagrant --> https://github.com/hashicorp/vagrant/blob/master/keys/vagrant

**Comment by ava-dylang** [comment]
Ah, its been a while. IIRC vagrant rotates the key on first login - I still don't quite understand how thats applicable in an ansible task. Is the ansible->vagrant component worth explaining to a casual observer as myself?
Side note, I might suggest keeping that keyfile named "vagrant" as to keep rando's like me from pointing and wondering.
Have a nice day 🙇

**Comment by ericpulvino** [comment]
Indeed we aren't actually using these playbooks with Vagrant. We're using it with another hypervisor/automation solution and have just gotten used to pre-loading the well-known vagrant key for simplicity across different simulation environments.
